### ISSUE TITLE
Could you provide a text insertion example ?

### ISSUE THREAD

**Issue by elliarbtan** [igorxut/vue-ckeditor5#14]
Hi

I need to insert text into the editor (and not replace full text value)

The [ckeditor5 documentation](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html#function-insertText) states insertion is done this way :

`model.change( writer => {
    writer.insertText( 'foo', paragraph, 'end' );
} );`

But I can't find a way to get the `model` from the component . It would be very kind from you (and useful) to add a text insertion example in the README, assuming I won't be the only one running into this problem.

Thanks.

**Comment by igorxut** [comment]
If you want to insert text to first position or last position, you can do it easily with operating 'v-model': https://jsfiddle.net/igorxut/9hka5qjn/

But other cases are more complicated. [Position](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_position-Position.html)

Please describe your working scenario.
