### ISSUE TITLE
Editor hang on init

### ISSUE THREAD

**Issue by 1dnmr** [igorxut/vue-ckeditor5#16]
Hi,

Can't use editor because it's hanging the page for the 5 seconds. At once Google Chrome even stopped the application with infinite loop warning. Unfortunately I did not copy call stack.

**Comment by igorxut** [comment]
Hello. Please, download directory [examples](https://github.com/igorxut/vue-ckeditor5/tree/master/examples) and  check all `index.html` files in your browser.  
I can't say anything else because you don't provide me information to research your problem.

**Comment by 1dnmr** [comment]
@igorxut
Hi! You can check with any of examples actually. Just add 20-30 instances of editor with moderate length text (500 symbols are ok). Browser hang for 5-8 seconds in my case on initialisation or v-model update.

**Comment by igorxut** [comment]
Please, check [this example](https://jsfiddle.net/igorxut/4zgs19cr/). Push `Run` and look console log.

100 instances of editor, 500 symbols.

Slow start but works. Time of initialization of all 100 instances ~13 seconds for me.  
I can't find any problems with updating v-model or infinite loops.

Anyway, what case do you have? Are you sure you need 20 instances on page?

You can use [async components](https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components) to resolve problem with hanging.

**Comment by 1dnmr** [comment]
@igorxut yes, this is what i mean. I also did not find any infinite loop. But anyways, compare to other editors it's quite long time.
Thanks for hinting about async components. May be it's my case.
About time - this is not your fault. It's slow CKEditror itself.
