### ISSUE TITLE
The global CKEDITOR_VERSION constant has already been set.

### ISSUE THREAD

**Issue by mbengchan** [igorxut/vue-ckeditor5#17]
I just installed the plugin and initialized the classic editor and everything was fine.
But when i did this

```
import Vue from 'vue'
import ClassicEditor from '@ckeditor/ckeditor5-build-classic'
import DocumentEditor from '@ckeditor/ckeditor5-build-decoupled-document'
import VueCkeditor from 'vue-ckeditor5'

const options = {
  editors: {
    // classic: ClassicEditor,
    document: DocumentEditor
  },
  name: 'ckeditor',
  height: 500
}

Vue.use(VueCkeditor.plugin, options);
```
i got this error

```
ckeditor-version-collision: The global CKEDITOR_VERSION constant has already been set. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-version-collision
Object { collidingVersion: "11.2.0", version: "11.2.0" }
```

**Comment by igorxut** [comment]
Information about that in [documentation](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-3-using-two-different-editors).

I recommended to create ["super build"](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/advanced-setup.html#creating-super-builds).

For example check my [gits](https://gist.github.com/igorxut/7958be654134b7475466ed3b85b7fbee).

Look [example1](https://raw.githubusercontent.com/igorxut/vue-ckeditor5/master/examples/example1/index.html) for using this build.

**Comment by mbengchan** [comment]
@igorxut please can you direct me on how to create a supper build?

**Comment by igorxut** [comment]
@Shadomax
Look links from my previous message.

You can fork [ckeditor5-build-classic](https://github.com/ckeditor/ckeditor5-build-classic) for example, and modify (with features what you want) at least 3 files (check my gits): package.json, ckeditor.js, webpack.config.js.

**Comment by mbengchan** [comment]
Thanks.
