### ISSUE TITLE
language not working!

### ISSUE THREAD

**Issue by standfv** [igorxut/vue-ckeditor5#19]
<ckeditor id="editor" :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>

editorConfig: {
    language: 'uk',
}

it's not change languague??

**Comment by igorxut** [comment]
Do you have such language in your bundle? Read [official documentation](https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html).

**Comment by usb248** [comment]
Why it's closed ? I imported language file and the option do anything
