### ISSUE TITLE
How to add Image contextual toolbar plugin

### ISSUE THREAD

**Issue by minasm** [igorxut/vue-ckeditor5#23]
How to add plugins using the options object?

```
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';

const options = {
  editors: {
    classic: ClassicEditor,
  },
  name: 'ckeditor'
}
Vue.use(VueCkeditor.plugin, options);
```
When I try to add any plugin I get ` ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated` error in the console and buttons from the toolbar disappears

This is what I tried
```
    import ClassicEditor from '@ckeditor/ckeditor5-build-classic'
    import VueCkeditor from 'vue-ckeditor5'
    import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';

    const options = {
        editors: {
            classic: ClassicEditor,
        },
        plugins: [ImageToolbar],
        toolbar: [ 'imageTextAlternative', '|', 'imageStyle:full', 'imageStyle:side' ],
        name: 'ckeditor'
    }

    Vue.use(VueCkeditor.plugin, options);
```

**Comment by mclintprojects** [comment]
I'm also trying to add text alignment and this is the same error I'm getting. @igorxut do you know how to fix this? I'm happy to implement the code for you.

**Comment by minasm** [comment]
Closing this one as I found [Trix editor](https://github.com/basecamp/trix) easier to implement with very similar features with ckeditor5. @mclintprojects you may also check it if you are still struggling with CKeditor 5.
