### ISSUE TITLE
error when used with draggable

### ISSUE THREAD

**Issue by odparraj** [igorxut/vue-ckeditor5#7]
Hello, I am trying to use your component in an ordered and dynamic list, that is, I can add elements on the fly, your plugin works perfect if I use it in a V-FOR but it fails if I use it in conjunction with the VUE.DRAGGABLE plugin, the editor does not allow me to modify the text.

any idea how I can fix it

![ezgif com-crop](https://user-images.githubusercontent.com/9358581/45572114-0368b400-b82e-11e8-9e2a-d74951f668e9.gif)

**Comment by igorxut** [comment]
Hello.

[The reason of that](https://github.com/RubaXa/Sortable#handle-option).

Use '[handle option](https://github.com/SortableJS/Vue.Draggable#options)' .

[Example](https://jsfiddle.net/igorxut/db9c4e7y/)
