### ISSUE TITLE
How to add table?

### ISSUE THREAD

**Issue by t0n1zz** [igorxut/vue-ckeditor5#8]
Hi, how to add table into ckeditor5 for vue? i tried to do
```
npm install --save @ckeditor/ckeditor5-table
```

and then import this
```
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
```

and put it into editor 
```
editors: {
 classic: ClassicEditor,
 table: Table,
 toolbar: TableToolbar
},
```

and in the template is
```
<vue-ckeditor type="classic" v-model="form.content" :editors="editors"></vue-ckeditor>
```

but i got the ckeditor with only paragraph button only... all other button is gone...

**Comment by igorxut** [comment]
Hello.  
'CKEditor 5 table feature' is not editor. It is plugin for editor.  
You must create a custom build with this plugin to use it.
Read [this](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html#adding-features)  and [this](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) and [this](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html)

**Comment by igorxut** [comment]
Table feature is default for [Document editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/overview.html#document-editor)

But if you want to use it with 'Classic editor' clone [classic build repository](https://github.com/ckeditor/ckeditor5-build-classic) and create custom build of it.

In 'package.json' add devDependecy:

```json
"@ckeditor/ckeditor5-table": "^10.1.0"
```

In 'src/ckeditor.js' install plugin and configure toolbar like [this file](https://github.com/ckeditor/ckeditor5-build-decoupled-document/blob/master/src/ckeditor.js)

If you want to change name of editor library (for example 'CustomEditor') change it in 'webpack.config.js'.

**Comment by t0n1zz** [comment]
hmmm i am getting confuse so which solution is should follow? the first one or the second? what i want is a wysiwyg editor that support most common feature like image upload, table, paragraph, bullet/number list, link, and some font styling

**Comment by igorxut** [comment]
[Choose interface](https://ckeditor.com/ckeditor-5/) what you like: Classic, Balloon, Inline, Document.

Clone repository from [list](https://github.com/ckeditor/ckeditor5#builds).

Create custom build with [features](https://github.com/ckeditor/ckeditor5#features) what your want.

It's easy, change only 3 files: 'package.json', 'src/ckeditor.js', 'webpack.config.js'.

**Comment by t0n1zz** [comment]
okay so i decided to use document interface and from what i learn from using classic interface i just need to import
```
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';
```

and then in my editor props i do 
```
editors: {
   document: DecoupledEditor
},
```

and last in my template it will be
```
<vue-ckeditor type="document" v-model="form.content" :editors="editors"></vue-ckeditor>
```

but the editor didn't render anything... just blank and i don;t find any error on console...

**Comment by igorxut** [comment]
[The decoupled editor requires you to inject the toolbar into the DOM](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html#document-editor).

I added new property 'toolbarContainer' to do that in VueCkeditor5 0.3.0.
Please updates and see [example](https://github.com/igorxut/vue-ckeditor5/tree/master/examples/example4).

**Comment by t0n1zz** [comment]
okay i tried exactly like the example with vueckeditor updated to 0.3.0, what i get is the document style textarea but without toolbars... why is that?

**Comment by igorxut** [comment]
I checked 'example4' in Google Chrome, Mozilla Firefox and Microsoft Edge. It works.
I made [jsfiddle](https://jsfiddle.net/igorxut/taLmvq31/) for you.

**Comment by t0n1zz** [comment]
okay i managed to do that.... and it works but i found some bugs in your css style on example4, when you put image into the editor, the caption area for the image is using the `min-height: 21cm` so i just remove the `min-height: 21cm;` on line 42 at ckeditor-document-style.css files and also changing the width from fixed pixel size into 98% so the document will match the screen size and optimized use the empty space

**Comment by t0n1zz** [comment]
hmmm and now i get error "ckeditor-version-collision: The global CKEDITOR_VERSION constant has already been set." if i am using/import 2 more than 1 build on the vue spa project.. .even when i do the exact same code like here (for testing purpose)
```
import DocumentEditor from '@ckeditor/ckeditor5-build-decoupled-document';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import BalloonEditor from '@ckeditor/ckeditor5-build-balloon'
import VueCkeditor from 'vue-ckeditor5';

const options = {
  editors: {
    classic: ClassicEditor,
    balloon: BalloonEditor,
    document: DocumentEditor
  },
  name: 'ckeditor'
}
```

**Comment by pdpotter** [comment]
The table feature is enabled in the [latest version](https://github.com/ckeditor/ckeditor5-build-classic/releases/tag/v11.1.0) of the classic build by default.

**Comment by igorxut** [comment]
> okay i managed to do that.... and it works but i found some bugs in your css style on example4

It is copy from [official documentation](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/ui/document-editor.html#the-user-interface).

---

> hmmm and now i get error "ckeditor-version-collision: The global CKEDITOR_VERSION constant has already been set." if i am using/import 2 more than 1 build on the vue spa project.. .even when i do the exact same code like here (for testing purpose)

I see. I found new information about that in [documentation](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-3-using-two-different-editors).
I recommended to create ["super build"](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/advanced-setup.html#creating-super-builds).

For example check my [gits](https://gist.github.com/igorxut/7958be654134b7475466ed3b85b7fbee).

I updated [example1](https://raw.githubusercontent.com/igorxut/vue-ckeditor5/master/examples/example1/index.html) for using this build.
